name = "eyeclinic-mmc"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[[pages_build_config]]
# Build command and output directory
build_command = "npm run build"
destination_dir = "dist"
